#!/bin/tcsh
#14/03/2018 - TK
#This script uses the buried surface area (BSA) scores that are extracted by the script named "get_BSA".
#The extracted BSA scores of a HADDOCK run are ranked and the highest score is selected as the best score.
#This process is iterated over each HADDOCK run output folder, collecting and listing the best scores of all of the HADDOCK runs in a given directory.

foreach i (BINDKIN*)
	echo $i >> dockingruns
	mv dockingruns $i/structures/it1/water/
	cd $i/structures/it1/water/
	cat valBSA | sed 's/\./,/g' | sort -nk2 | tail -1 > max_$i
	paste dockingruns max_$i >> maxenergies_$i
	mv maxenergies_$i ../../../../
	rm dockingruns max_$i
	cd ../../../../
end
cat maxenergies* >> maximum
cat maximum | awk '{print $1,$3}' | sed 's/100_//g' >> maximumvalHOH_BSA
rm maxenergies* maximum
