#!/bin/tcsh
#29/11/18 - tk

foreach i(BINDKIN*)
	cd $i/structures/it1/water
	foreach j(*.pdb)
		grep energies $j | awk '{print $8}' | sed 's/,//g' >> vdw
		echo $j >> pdblist
		paste pdblist vdw | awk '{print $1,$2}' > valVDW
	end
	cd ../../../../
end
