#!/bin/tcsh
#29/11/18 - tk

foreach i(BINDKIN*)
	cd $i/structures/it1/water
	foreach j(*.pdb)
		grep energies $j | awk '{print $9}' | sed 's/,//g' >> elec
		echo $j >> pdblist
		paste pdblist elec | awk '{print $1,$2}' > valELEC
	end
	cd ../../../../
end
